version: '3'

services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:nightly
    ports:
      - "${PORT}:80" # Importante: Railway asigna el puerto din√°micamente
    environment:
      - APP_URL=${APP_URL}
      - DB_CONNECTION=mysql
      - DB_HOST=${MYSQLHOST}
      - DB_PORT=${MYSQLPORT}
      - DB_DATABASE=${MYSQLDATABASE}
      - DB_USERNAME=${MYSQLUSER}
      - DB_PASSWORD=${MYSQLPASSWORD}
    restart: always
